# Generated by Django 4.2.5 on 2023-09-05 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year_of_issue',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
