# Generated by Django 4.2.5 on 2023-09-05 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0001_initial'),
        ('album', '0002_album_year_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='singer.singer', verbose_name='Исполнитель'),
        ),
    ]
