version: "3.0"
services:
  db:
    container_name: "database_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  app:
    build:
      context: .
    env_file:
      - .env.example
    container_name: "test_app"
    command: >   
      sh -c "sleep 2s
      && python3 manage.py migrate
      && sleep 2s
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db

